version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Resolving dependencies..."
      - mvn -B dependency:go-offline


  build:
    commands:
      - echo "Running mvn package..."
      - mvn -B clean package -DskipTests
      - echo "Checking target directory..."
      - ls -lah target/

  post_build:
    commands:
      - echo "Build finished on $(date)"

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
    - postscript.sh
  discard-paths: no